// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public, non-secret values. Kept as fallbacks so the published build never
// initializes with `undefined` if build-time env vars are missing.
const FALLBACK_SUPABASE_URL = 'https://qdpqfsqjtbvlulekfhoy.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcHFmc3FqdGJ2bHVsZWtmaG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MzgyODksImV4cCI6MjA4NTAxNDI4OX0.Rqw-1Lx1Uo5Ar8stFQv4fPE7OkmAlamz21T3BAZocPw';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});